service: tusers

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: ${opt:stage}
  environment: ${file(env.${opt:stage, self:provider.stage}.json)}
  apiGateway:
    shouldStartNameWithService: true

package:
  #  include:
  #    - include-me.js
  #    - include-me-dir/**
  
   
functions:
  app:
    handler: handler.Server
    events:
      - http:
          path: /user/{proxy+}
          method: any
          cors:
            origin: "*"
            headers: # <-- Specify allowed headers
              - Content-Type
            allowCredentials: false
          
plugins:
  - serverless-offline